<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */
?>

<?php
$_objectManager = \Magento\Framework\App\ObjectManager::getInstance(); //instance of\Magento\Framework\App\ObjectManager
$storeManager = $_objectManager->get('Magento\Store\Model\StoreManagerInterface'); 
$currentStore = $storeManager->getStore();
$baseUrl = $currentStore->getBaseUrl();
$mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);

?>

<div data-block="minicart" class="minicart-wrapper">
    <a class="action showcart" href="<?php /* @escapeNotVerified */ echo $block->getShoppingCartUrl(); ?>"
       data-bind="scope: 'minicart_content'">
        <!--<span class="text"><?php /* @escapeNotVerified */ //echo __('My Cart'); ?></span>-->
        <span class="cart_icon_qty_ki"><!-- <i class="fa fa-shopping-cart"></i> -->
            <img src="<?php echo $mediaUrl;  ?>cart.png"  style="width:27px">
        </span>
        <span class="counter qty empty item_qty_ki" 
              data-bind="css: { empty: !!getCartParam('summary_count') == false }, blockLoader: isLoading">
            <span class="counter-number" value=""><!-- ko text: getCartParam('summary_count') -->0<!-- /ko --></span>
            <span class="counter-label">
            <!-- ko if: getCartParam('summary_count') -->
                <!-- ko text: getCartParam('summary_count') --><!-- /ko -->
                <!-- ko i18n: 'items' --><!-- /ko -->
            <!-- /ko -->
            </span>
        </span>
        <span class="cartmini">Cart</span>
		
    </a><!-- <span class="cart-text">
                    <span class="cart-count"> -->
                    <!-- <span class="badge">
                    <?php 
                        $helper = $this->helper('\Magento\Checkout\Helper\Cart');
                        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                        $currencysymbol = $objectManager->get('Magento\Store\Model\StoreManagerInterface');
                        $currency = $currencysymbol->getStore()->getCurrentCurrencyCode();
                        echo $currency.number_format($helper->getQuote()->getSubtotal(), 2, '.', '');
                    ?>
                 
                    </span>
                </span> 
                </span> --> 

    <?php if ($block->getIsNeedToDisplaySideBar()): ?>
        <div class="block block-minicart empty"  
             data-role="dropdownDialog"
             data-mage-init='{"dropdownDialog":{
                "appendTo":"[data-block=minicart]",
                "triggerTarget":".showcart",
                "timeout": "2000",
                "closeOnMouseLeave": false,
                "closeOnEscape": true,
                "triggerClass":"active",
                "parentClass":"active",
                "buttons":[]}}'>
            <div id="minicart-content-wrapper" data-bind="scope: 'minicart_content'">
                <!-- ko template: getTemplate() --><!-- /ko -->
            </div>
            <?php //echo $block->getChildHtml('minicart.addons'); ?>
        </div>
    <?php endif ?>
    <script>
        window.checkout = <?php /* @escapeNotVerified */ echo \Zend_Json::encode($block->getConfig()); ?>;
    </script>
    <script type="text/x-magento-init">
    {
        "[data-block='minicart']": {
            "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
        },
        "*": {
            "Magento_Ui/js/block-loader": "<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
        }
    }
    </script>
</div>


