<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Login $block */
?>
<?php
/**
 * Customer login form template
 *
 * @see \Magento\Customer\Block\Form\Login
 * @var $block \Magento\Customer\Block\Form\Login
 */
?>
<div class="">

<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 sign_block_l block block-customer-login login_custom">

    <a href="<?php echo $block->getBaseUrl(); ?>">
        <span>
            <img class="img-responsive logo_tm_l" src="<?php echo $block->getViewFileUrl('Magento_Catalog::images/logo_tm.png')?>">
        </span>
      </a>

<div class="form_cont sign_form_l">
    <div class="block-title">
        <h3 id="block-customer-login-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo __('Sign in') ?></h3>
    </div>
    <div class="block-content" aria-labelledby="block-customer-login-heading">
        <form class="form form-login"
              action="<?php /* @escapeNotVerified */ echo $block->getPostActionUrl() ?>"
              method="post"
              id="login-form"
              data-mage-init='{"validation":{}}'>
            <?php echo $block->getBlockHtml('formkey'); ?>
            <fieldset class="fieldset login">
                <div class="field note"><?php /* @escapeNotVerified */ echo __('If you have an account, sign in with your mobile number.') ?></div>
                <div class="field email required">
                    <label class="label" for="email"><span><?php /* @escapeNotVerified */ echo __('Mobile Number') ?></span></label>
                    <div class="control">
                        <input name="login[username]" value="+880<?php echo $block->escapeHtml($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()) :?> autocomplete="off"<?php endif; ?> id="email" type="text" class="input-text emailandmob" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" data-validate="{required:true}" placeholder="Enter Mobile Number">
                        <!-- magecomp start -->
                        <div for="email" style="color:#e02b27;display:none; font-size: 1.2rem;" id="custom-email-error" >Please enter valid number/email.</div>
                        <!-- magecomp end -->
                    </div>
                </div>
                <div class="field password required">
                    <label for="pass" class="label">
                        <span><?php /* @escapeNotVerified */ echo __('Password') ?></span>
                    </label>
                    <div class="secondary">
                        <a class="action remind forgot_pass_l" href="<?php /* @escapeNotVerified */ echo $block->getForgotPasswordUrl() ?>">
                            <span><?php /* @escapeNotVerified */ echo __('Forgot Your Password?') ?></span>
                        </a>
                    </div>
                    <div class="control">
                        <input name="login[password]" type="password" <?php if ($block->isAutocompleteDisabled()) :?> autocomplete="off"<?php endif; ?> class="input-text" id="pass" title="<?php /* @escapeNotVerified */ echo __('Password') ?>" data-validate="{required:true, 'validate-password':true}" placeholder="Enter Password">
                    </div>
                </div>
                <?php echo $block->getChildHtml('form_additional_info'); ?>
                <div class="actions-toolbar">
                    <div class="btn_custom_sign">
                        <button type="submit" class="btn action login primary login_verify" name="send" id="send2">
                            <span><?php /* @escapeNotVerified */ echo __('Sign in') ?></span>
                        </button>
                    </div>
                </div>

                <div class="signned_details">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 keepmesignned">
                        <div class="check_sign">
                            <input type="checkbox" name="keep">
                        </div>
                        <div class="check_details">
                            <span>Keep me signed in.</span>
                            <!-- Trigger/Open The moda1 -->
                            <span><a href="#" id="mydtl"> Details</a></span>
                        </div>
                    </div>

                    <!-- The moda1 -->
                    <div id="myModa1" class="moda1">
                          <!-- moda1 content -->
                          <div class="moda1-content">
                            <div class="moda1-header">
                              <span class="close">&times;</span>
                              <h2>"Keep Me Signed In" Checkbox</h2>
                            </div>
                            <div class="moda1-body">
                              <p>If this is a personal device that you don't share with others, we recommend that you check the "Keep me signed in" checkbox. This will keep you signed in to your KiKinben account on this device, so you'll be asked to sign in less frequently. To make sure that your account remains safe, we may still occasionally ask you to confirm your identity - for example, by entering your password, or responding to a message on your mobile device.</p>
                              <p>To prevent others from accessing your KiKinben account, we strongly recommend that you don't use this feature on devices and computers that are shared with other people.</p>
                            </div>
                          </div>

                    </div>
                </div>


                
                <div class="block_tit_sign">
                    <div class="block_sign_tit">
                    <h5 id="block-new-customer-heading" aria-level="2"><?php /* @escapeNotVerified */ echo __('New to KiKinben?') ?></h5>
                    </div>

                    <div class="block-content" aria-labelledby="block-new-customer-heading">
                        <div class="actions-toolbar">
                            <div class="primary btn btn-custom2">
                                <a href="<?php echo $this->getUrl('customer/account/create'); ?>" class="action create primary">
                                <span><?php /* @escapeNotVerified */ echo __('Create your KiKinben account') ?></span></a>
                            </div>
                        </div>
                    </div>
                </div>

            </fieldset>
        </form>
    </div>
</div>
	
<div class="container-fluid">
    <div class="signIn_footer">
      <div class="signIn_footer_nav">
        <ul>
          <li><a target="_blank" href="<?php echo $this->getUrl('conditions-of-use');?>">Conditions of Use</a></li>
          <li><a target="_blank" href="<?php echo $this->getUrl('privacy-notice');?>">Privacy Notice</a></li>
          <li><a target="_blank" href="<?php echo $this->getUrl('faq-new');?>">Help</a></li>
        </ul>
      </div>

      <div class="copyright_blk_new">
        <p>© 2016-2017 kikinben.com | The Kikinben logo is a Registered Trademark of Kikinben</p>
      </div>
    </div>
  </div>
	
	
</div>

<!--<div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 sign_image">
    <img class="img-responsive" src="<?php echo $block->getViewFileUrl('Magento_Catalog::images/sign_in.png')?>">
</div>-->

</div>

<!-- magecomp start -->
<script type="text/javascript">
jQuery(document).ready(function(e) {
	
    jQuery('#login-form').submit(function() {
		var username = jQuery("#email").val();
		jQuery("#custom-email-error").css('display','none');
		jQuery("#email").removeClass("mage-error");
		if(jQuery.isNumeric(username)){
			if(username.length < 10 ){
				jQuery("#custom-email-error").css('display','block');
				jQuery("#email").addClass("mage-error");
				return false;
			}
		}
		else if(!isEmail(username)){
			
				jQuery("#custom-email-error").css('display','block');
				jQuery("#email").addClass("mage-error");
				return false;
		}
		

  // your code here
	});
	function isEmail(email) {
		  var regex = /^([a-zA-Z0-9_.+-])+\@(([a-zA-Z0-9-])+\.)+([a-zA-Z0-9]{2,4})+$/;
		  return regex.test(email);
		}
	
});



        // Get the moda1
        var moda1 = document.getElementById('myModa1');

        // Get the button that opens the moda1
        var btn = document.getElementById("mydtl");

        // Get the <span> element that closes the moda1
        var span = document.getElementsByClassName("close")[0];

        // When the user clicks the button, open the moda1 
        btn.onclick = function() {
            moda1.style.display = "block";
        }

        // When the user clicks on <span> (x), close the moda1
        span.onclick = function() {
            moda1.style.display = "none";
        }

        // When the user clicks anywhere outside of the moda1, close it
        window.onclick = function(event) {
            if (event.target == moda1) {
                moda1.style.display = "none";
            }
        }


</script>

<script>
require([ 'jquery', 'intlTelInput'], function($){
  $(document).ready(function(){
   	$("#email").intlTelInput({
		//excludeCountries: ["us"],
		//onlyCountries: ['us', 'gb', 'ch', 'ca', 'do', 'in'],
	});
  });
});
</script>
<!-- magecomp end -->
