 <fieldset class="fieldset create account" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
        <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Additional Information') ?></span></legend><br></p>
 
<p>        <div class="field my_attribute required">
            <label for="mobilenumber" class="label"><span><?php /* @escapeNotVerified */ echo __('mobilenumber') ?></span></label>
            <div class="control">
                <input type="text" name="mobilenumber" id="mobilenumber" title="<?php /* @escapeNotVerified */ echo __('mobilenumber') ?>" class="input-text" data-validate="{required:true}" autocomplete="off">
            </div>
        </div>
        </div>
    </fieldset>