<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 * @category    Apptha
 * @package     Apptha_Marketplace
 * @version     1.1
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2016 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 * */
?>
<?php

use Magento\Framework\App\Action\Action;
$_productCollection = $block->getCollection ();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance ();
$dataHelper = $objectManager->get ( 'Apptha\Marketplace\Helper\Data' );
$stores = $objectManager->get ( '\Magento\Store\Model\StoreManagerInterface' );

$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_aloHelper = $this->helper('Magiccart\Alothemes\Helper\Data');
$imagehelper = $this->helper ( 'Magento\Catalog\Helper\Image' );

$baseUrl = $stores->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_LINK);

function truncateStringWords($str, $maxlen)
{
	if (strlen($str) <= $maxlen) return $str;

	$newstr = substr($str, 0, $maxlen);
	if (substr($newstr, -1, 1) != ' ') $newstr = substr($newstr, 0, strrpos($newstr, " "));

	return $newstr;
}

?>


<?php if (empty($_productCollection)): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>

<div class="toolbar-top">
        <?php echo $block->getToolbarHtml() ?>
    </div>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
		
		echo $_aloHelper->getGridStyle('.product-items .product-item'); // Config Product Grid
    } else {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    
    ?>
    
    <div id='display_products_all' class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php echo $viewMode; ?> category-product-<?php echo $viewMode; ?>">
     <?php $iterator = 1; ?>
     <ol class="products list items product-items">
     <?php foreach ($_productCollection as $_product): ?>
     
     <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
     <!-- mode view grid -->
                
                <?php  $productImage = $imagehelper->init ( $_product, 'category_page_grid' )->constrainOnly ( FALSE )->keepAspectRatio ( TRUE )->keepFrame ( FALSE )->resize ( 240, 300 )->getUrl ();?>
			   <div class="product-item-info" data-container="product-grid">
				    <div class="images-container">
					    <?php
								$_productNameStripped = $block->stripTags($_product->getName(), null, true);
							?>
							<h2 class="product-name product-item-name">
								<a class="product-item-link"
								   href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
									<?php /* @escapeNotVerified */ echo ucfirst(strtolower($_helper->productAttribute($_product, truncateStringWords($_product->getName(),28), 'name')))."..."; ?>
								</a>
							</h2>
						<div class="product-hover">	
							<?php
							
							if ($pos != null) {
								$position = ' style="left:' . $productImage->getWidth() . 'px;'
									. 'top:' . $productImage->getHeight() . 'px;"';
							}
							?>
							<?php // Product Image ?>
							<?php echo $_aloHelper->getLabels($_product); ?>
							<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
								<img class="product-image-photo" src="<?php echo $productImage;?>"
								alt="<?php echo $_product->getName();?>">
							</a>
						</div>
						
						<div class="hover-box">
							<div class="rating">
								<?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                            </div>

							<?php if ($showDescription):?>
								<div class="short-desc">
									<div class="product description product-item-description">
										<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
										<!--<a href="<?php /* @escapeNotVerified */ //echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */ //echo $_productNameStripped ?>"
										   class="action more"><?php /* @escapeNotVerified */ //echo __('Learn More') ?></a>-->
									</div>
								</div>
							<?php endif; ?>
							<div class="sku">
                                <label><?php /* @escapeNotVerified */ echo __('Sku:') ?> </label><?php echo $_helper->productAttribute($_product, $_product->getSku(), 'sku') ?>
                            </div>
							<div class="product details product-item-details">
							    <?php echo $block->getProductDetailsHtml($_product); ?>
								<div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
									<?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
									<div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
										<?php if ($_product->isSaleable()): ?>
											<?php $postParams = $block->getAddToCartPostParams($_product); ?>
											<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
												<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
												<input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
												<?php echo $block->getBlockHtml('formkey')?>
												<button type="submit"
														title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
														class="action button tocart primary">
													<i class="icon icon-add-to-cart"></i>
													<span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
												</button>
											</form>
										<?php else: ?>
											<?php if ($_product->getIsSalable()): ?>
												<div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
											<?php else: ?>
												<div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
											<?php endif; ?>
										<?php endif; ?>
									</div>
									<div data-role="add-to-links" class="actions-secondary add-to-links"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
										<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
											<a href="#"
											   class="action towishlist"
											   title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
											   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
											   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
											   data-action="add-to-wishlist"
											   role="button">
												<i class="icon icon-favorites"></i><?php /* @escapeNotVerified */ echo __('Wishlist') ?>
											</a>
										<?php endif; ?>
										<?php
										$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
										?>
										<a href="#"
										   class="action tocompare"
										   title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
										   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
										   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
										   role="button">
											<i class="icon icon-compare"></i><?php /* @escapeNotVerified */ echo __('Compare') ?>
										</a>
									</div>
								</div>
							</div>
						</div>
					</div>
                </div>
				
								
     <?php echo($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
     <?php endforeach;?>
     
     </ol>
    </div>
<script type="text/javascript">	
	
	function getSellerProducts(sellerId,categoryId){
		require(
		        ['jquery','ajaxmenu'],
		        function($,ajaxmenu){
		        	var baseurl = "<?php echo $baseUrl;?>";
		    		var sellerProductUrl = baseurl+'kikinben_sellercategory/index/index/id/'+sellerId+'/catgid/'+categoryId;
		        	ajaxmenu.ajaxMenu(sellerProductUrl,sellerId,categoryId);

		    }); 

	}
</script>
<div id="display_products"></div>

<div class="toolbar-bottom toolbar-view-<?php echo $viewMode;?>">
        <?php echo $block->getToolbarHtml() ?>
</div>
    <?php /* if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; */ ?>
<?php endif;?>
<script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
</script>