<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper('Magento\Search\Helper\Data');
?>
<div class="block-search">
    <div class="block block-content">
        <form class="form minisearch form-search" id="search_mini_form" action="<?php /* @escapeNotVerified */ echo $helper->getResultUrl() ?>" method="get">
		    <div class="block-title"><strong><?php /* @escapeNotVerified */ echo __('Search'); ?></strong></div>
            <button type="submit"
                    title="<?php echo $block->escapeHtml(__('Search')) ?>"
                    class="action search button">
                <span><span class="icon icon-search"><?php /* @escapeNotVerified */ //echo __('Search'); ?></span></span>
            </button>
            <div class="search_dropdown">
                <select class="selecttext" id="dropdown" name="select">
                  <option value="all">All Categories</option>
                  <option value="whatsnew">Kikinben Launching Offer</option>
                  <option value="phonestabletsaccessories">Phones, Tablets &amp; Accessories</option>
                  <option value="computerselectronics">Computers &amp; Electronics</option>
                  <option value="tvaudiogaming">TV, Audio &amp; Gaming</option>
                  <option value="makeupglam">Makeup &amp; Glam</option>
                  <option value="mensfashion">Men's Fashion</option>
                  <option value="womensfashion">Women's Fashion</option>
                  <option value="toyskidsbaby">Toys, Kids &amp; Baby</option>
                  <option value="kitchenhomeappliances">Kitchen &amp; Home Appliances</option>
                  <option value="homedecor">Home &amp; Decor</option>
                  <option value="bagsluggages">Bags &amp; Luggages</option>
                  <option value="buildingconstructions">Building &amp; Constructions</option>
                  <option value="healthbeautyfragrances">Health, Beauty &amp; Fragrances</option>
                </select>
            </div>
            <div class="field search">
                <div class="control">
                    <input id="search"
                           data-mage-init='{"quickSearch":{
                                "formSelector":"#search_mini_form",
                                "url":"<?php /* @escapeNotVerified */ echo $block->getUrl('search/ajax/suggest'); ?>",
                                "destinationSelector":"#search_autocomplete"}
                           }'
                           type="text"
                           name="<?php /* @escapeNotVerified */ echo $helper->getQueryParamName() ?>"
                           value="<?php /* @escapeNotVerified */ echo $helper->getEscapedQueryText() ?>"
                           placeholder="<?php /* @escapeNotVerified */ echo __('Search for product'); ?>"
                           class="input-text"
                           maxlength="<?php /* @escapeNotVerified */ echo $helper->getMaxQueryLength();?>"
                           role="combobox"
                           aria-haspopup="false"
                           aria-autocomplete="both"
                           autocomplete="off"/>
                    <div id="search_autocomplete" class="search-autocomplete"></div>
                    <?php echo $block->getChildHtml() ?>

                </div>

            </div>
        </form>
    </div>
</div>
