<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper('Magento\Search\Helper\Data');
?>
<div class="block-search">
    <div class="block block-content">
        <form class="form minisearch form-search" id="search_mini_form" action="<?php /* @escapeNotVerified */ echo $helper->getResultUrl() ?>" method="get">
		    <div class="block-title"><strong><?php /* @escapeNotVerified */ echo __('Search'); ?></strong></div>
            <button type="submit"
                    title="<?php echo $block->escapeHtml(__('Search')) ?>"
                    class="action search button">
                <span><span class="icon icon-search"><?php /* @escapeNotVerified */ //echo __('Search'); ?></span></span>
            </button>
            <div class="search_dropdown">
                <select class="selecttext" id="dropdown" name="select">
                <option value="all">All Categories</option>
                 <option value="whatsnew">Kikinben Launching Offer</option>
                 <option value="makeup">Make Up</option>
                 <option value="healthbeautyfragrances">Health, Beauty and Fragrances</option>
                 <option value="mensfashon">Wen's Fashion</option>
                 <option value="toykidsbabys">Toy, Kid's and Baby</option>
                 <option value="phonesaccessories">Phones and Accessories</option>
                 <option value="tvaudiogames">TV, Audio and Games</option>
                 <option value="homecooking">Home and Cooking</option>
                 <option value="sportsoutdoorscycling">Sports, Outdoors and Cycling</option>
                 <option value="laptopdesktops">Laptops and Desktops</option>
                </select>
            </div>
            <div class="field search">
                <div class="control">
                    <input id="search"
                           data-mage-init='{"quickSearch":{
                                "formSelector":"#search_mini_form",
                                "url":"<?php /* @escapeNotVerified */ echo $block->getUrl('search/ajax/suggest'); ?>",
                                "destinationSelector":"#search_autocomplete"}
                           }'
                           type="text"
                           name="<?php /* @escapeNotVerified */ echo $helper->getQueryParamName() ?>"
                           value="<?php /* @escapeNotVerified */ echo $helper->getEscapedQueryText() ?>"
                           placeholder="<?php /* @escapeNotVerified */ echo __('Search for product'); ?>"
                           class="input-text"
                           maxlength="<?php /* @escapeNotVerified */ echo $helper->getMaxQueryLength();?>"
                           role="combobox"
                           aria-haspopup="false"
                           aria-autocomplete="both"
                           autocomplete="off"/>
                    <div id="search_autocomplete" class="search-autocomplete"></div>
                    <?php echo $block->getChildHtml() ?>

                </div>

            </div>
        </form>
    </div>
</div>
