<?php $formurl = $block->getUrl('registration/index/sendotp'); ?>

<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 mob_log">

<div class="create_account_float">
	<div class="mob_form">

	  <a href="<?php echo $block->getBaseUrl(); ?>">
	  	<span>
	  		<img class="img-responsive logo_tm_l" src="<?php echo $block->getViewFileUrl('Magento_Catalog::images/logo_tm.png')?>">
	  	</span>
	  </a>
  
		<form class="form create account form-create-account create_custom_l"
			action="<?php /* @escapeNotVerified */ echo $formurl ?>" method="post"
			id="form-validate" enctype="multipart/form-data" autocomplete="off">
			<fieldset class="fieldset create account"
				data-hasrequired="<?php echo __('* Required Fields') ?>">
				<div class="block field my_attribute required">
					<!-- <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 register_title">
						<h1 style="text-align: center;">Register</h1>
					</div> -->
	
               

					<div class="block-title block_title_custom">
				        <h3 id="block-customer-login-heading" role="heading" aria-level="2">Create account</h3>
				    </div>
					
					<!-- 
					<label for="mobilenumber" class="label"><span><?php echo __('Mobile Number (Ex:+880 1977 XXXXXX)') ?></span></label> -->
					<div class="control col-lg-12 col-md-12 col-sm-12 col-xs-12">
						<div class="row data-list-input-code cocode">
						<div>

							 <label class="tooltip_cust" style="float: right;font-weight: normal;margin-top: 0px;font-size: 13px;"><i class="fa fa-info"></i>
      							<span class="tooltiptext">Enter mobile number and get verification code</span>
      						</label>

							<label for="password" class="label"><span><?php /* @escapeNotVerified */ echo __('Enter Mobile Number') ?></span></label>
      </div>

		<div class="conv-wrap">
			<div class="conv-cont al-left">
				<form action="#" method="post" name="frm" class="cov-frm">
			<!-- <label class="cov-frm-label">Sending Amount</label> -->
					<div class="cov-inp-bx">
						<select class="selectpicker" name = "Cities" onChange="OnDropDownChange(this)">

        				<option data-icon="AU" value="+61"></option>
						<option data-icon="AT" value="+43">Austria(+43)</option>
						<option data-icon="BH" value="+973">Bahrain(+973)</option>
						<option data-icon="BD" value="+880" Selected>Bangladesh(+880)</option>
						<option data-icon="CA" value="+1">Canada(+1)</option>
						<option data-icon="CY" value="+90392">Cyprus North(+90392)</option>
						<option data-icon="CY" value="+357">Cyprus South(+357)</option>
						<option data-icon="DK" value="+45">Denmark(+45)</option>
						<option data-icon="FI" value="+358">Finland(+358)</option>
						<option data-icon="FR" value="+33">France(+33)</option>
						<option data-icon="DE" value="+49">Germany(+49)</option>
						<option data-icon="GR" value="+30">Greece(+30)</option>
						<option data-icon="HK" value="+852">Hong Kong(+852)</option>
						<option data-icon="ID" value="+62">Indonesia(+62)</option>
						<option data-icon="IE" value="+353">Ireland(+353)</option>
						<option data-icon="IT" value="+39">Italy(+39)</option>
						<option data-icon="JP" value="+81">Japan(+81)</option>
						<option data-icon="KR" value="+82">Korea South(+82)</option>
						<option data-icon="KW" value="+965">Kuwait(+965)</option>
						<option data-icon="MY" value="+60">Malaysia(+60)</option>
						<option data-icon="MV" value="+960">Maldives(+960)</option>
						<option data-icon="NZ" value="+64">New Zealand(+64)</option>
						<option data-icon="NO" value="+47">Norway(+47)</option>
						<option data-icon="OM" value="+968">Oman(+968)</option>
						<option data-icon="PT" value="+351">Portugal(+351)</option>
						<option data-icon="QA" value="+974">Qatar(+974)</option>
						<option data-icon="RU" value="+7">Russia(+7)</option>
						<option data-icon="SA" value="+966">Saudi Arabia(+966)</option>
						<option data-icon="SG" value="+65">Singapore(+65)</option>
						<option data-icon="ZA" value="+27">South Africa(+27)</option>
						<option data-icon="ES" value="+34">Spain(+34)</option>
						<option data-icon="LK" value="+94">Sri Lanka(+94)</option>
						<option data-icon="SE" value="+46">Sweden(+46)</option>
						<option data-icon="CH" value="+41">Switzerland(+41)</option>
						<option data-icon="TH" value="+66">Thailand(+66)</option>
						<option data-icon="AE" value="+971">UAE(+971)</option>
						<option data-icon="GB" value="+44">UK(+44)</option>
						<option data-icon="US" value="+1">USA(+1)</option>
    </select>

	<input class="data-list-input-code" required="required"
							data-validate="{required:true, required 'validate-number':true}" type="text"
							name="mobilenumber" id="mobilenumber" placeholder="+8801970112211" value="+880" pattern="^[+]\d{3}\d{4}\d{3}\d{3}$" />

						</div>

					</div>
				</div>
				</div>
				</div>
			</fieldset>
			<div class="actions-toolbar col-lg-12 col-md-12 col-sm-12 col-xs-12 reg_para">
			<p>By <b>Registering</b>, you agree that you've read and accepted our 
			<a href="#" style="color:#356ae7"><span>User Agreement</span></a>, you're at least 18 years old, and you consent to our 
			<a href="#" style="color:#356ae7"><span>Privacy Notice</span></a> and receiving marketing communications from us.</p>
				<div class="primary register_btn btn-custom">

					<button onclick="mobileNumber()" type="submit" class="login_verify action btn submit primary"
						title="<?php /* @escapeNotVerified */ echo __('Create an Account') ?>">
						<span><?php /* @escapeNotVerified */ echo __('Get verification code') ?></span>
					</button>
				</div>
				<div class="block_tit">
                    <div class="block_new_tit">
                    <h5 id="block-new-customer-heading" aria-level="2"><?php /* @escapeNotVerified */ echo __('Already have an account?') ?></h5>
                    </div>

                    <div class="block-content" aria-labelledby="block-new-customer-heading">
                        <div class="actions-toolbar action_custom_tools">
                            <div class="primary btn btn-custom2">
                                <a href="<?php echo $this->getUrl('customer/account/login'); ?>" class="action create primary">
                                <span><?php /* @escapeNotVerified */ echo __('Sign in') ?></span></a>
                            </div>
                        </div>
                    </div>
                </div>
			</div>

		</form>
	</div>
</div>



<!--<div class="col-lg-5 col-md-5 col-sm-12 col-xs-12 register_img">
	<img class="img-responsive" src="<?php echo $block->getViewFileUrl('Magento_Catalog::images/registration.png')?>">
</div>-->

</div>

<div class="container-fluid">
    <div class="signIn_footer">
      <div class="signIn_footer_nav">
        <ul>
          <li><a href="#">Conditions of Use</a></li>
          <li><a href="#">Privacy Notice</a></li>
          <li><a href="#">Help</a></li>
        </ul>
      </div>

      <div class="copyright_blk_new">
        <p>© 2017, kikinben.com | All Rights Reserved</p>
      </div>
    </div>
  </div>

<script type="text/javascript">
    function OnDropDownChange(dropDown) {
        var selectedValue = dropDown.options[dropDown.selectedIndex].value;
        document.getElementById("mobilenumber").value = selectedValue;
    }
 </script>

<!-- <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script> -->

<script>
function mobileNumber() {
    var x, text;

    // Get the value of the input field with id="numb"
    x = document.getElementById("numb").value;
    var phoneno = /^\+?([0-9]{2})\)?[-. ]?([0-9]{4})[-. ]?([0-9]{4})$/; 
    // If x is Not a Number or less than one or greater than 10
    if (isNaN(x) || x < 1 || x > 14) {
        alert("Input not valid");
    } else {
        text = "Input OK";
    }

}
</script>
 
<script>
jQuery(function() {
	$('select.data-list-input-code').focus(function() {
		$(this).siblings('input.data-list-input-code').focus();
	});
	$('select.data-list-input-code').change(function() {
		$(this).siblings('input.data-list-input-code').val($(this).val());
	});
    
	$('input.data-list-input-code').change(function() {
		$(this).siblings('select.data-list-input-code').val('');
	});
});
</script>

<script>

	function OnDropDownChange(dropDown) {
        var selectedValue = dropDown.options[dropDown.selectedIndex].value;
        document.getElementById("txtSelectedCity").value = selectedValue;
    }


  $(document).ready(function () {
    var mySelect = $('#first-disabled2');

    $('#special').on('click', function () {
      mySelect.find('option:selected').prop('disabled', true);
      mySelect.selectpicker('refresh');
    });

    $('#special2').on('click', function () {
      mySelect.find('option:disabled').prop('disabled', false);
      mySelect.selectpicker('refresh');
    });

    $('#basic2').selectpicker({
      liveSearch: true,
      maxOptions: 1
    });
  });
</script>
