<?php $formurl = $block->getUrl('registration/index/sendotp'); ?>

<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 mob_log">

<div class="create_account_float">
	<div class="mob_form">
		
<a href="<?php echo $block->getBaseUrl(); ?>"><span><img class="img-responsive logo_tm_l" src="<?php echo $block->getViewFileUrl('Magento_Catalog::images/logo_tm.png')?>"></span></a>
		<form class="form create account form-create-account"
			action="<?php /* @escapeNotVerified */ echo $formurl ?>" method="post"
			id="form-validate" enctype="multipart/form-data" autocomplete="off">
			<fieldset class="fieldset create account"
				data-hasrequired="<?php echo __('* Required Fields') ?>">
				<div class="block field my_attribute required">
					<!-- <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 register_title">
						<h1 style="text-align: center;">Register</h1>
					</div> -->
	
               

					<div class="block-title block_title_custom">
				        <h3 id="block-customer-login-heading" role="heading" aria-level="2">Create account</h3>
				    </div>
					<!--<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 register_name">
					<div class="row">
						<div class="col-lg-6 col-lg-6 col-md-6 col-xs-6">
							<label for="password" class="label"></label>
							<input class="input_first" type="text" name="fname" placeholder="First Name" title="First Name" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserName())?>">
						</div>
						<div class="col-lg-6 col-lg-6 col-md-6 col-xs-6">
							<label for="password" class="label"></label>
							<input class="input_second" type="text" name="lname" placeholder="Last Name" <?php echo $block->escapeHtml($block->getName()) ?>>
						</div>
					</div>
					</div>-->
					<!-- 
					<label for="mobilenumber" class="label"><span><?php echo __('Mobile Number (Ex:+880 1977 XXXXXX)') ?></span></label> -->
					<div class="control col-lg-12 col-md-12 col-sm-12 col-xs-12">
						<div class="row data-list-input-code cocode">

						<div>
						<label class="tooltip_cust" style="float: right;font-weight: normal;margin-top: 0px;font-size: 13px;"><i class="fa fa-info"></i>
      							<span class="tooltiptext">Enter mobile number and get verification code</span>
      						</label>

							<label for="password" class="label"><span><?php /* @escapeNotVerified */ echo __('Enter Mobile Number') ?></span></label>
							</div>

	<input class="data-list-input-code" required="required"
data-validate="{required:true, required 'validate-number':true}" type="text"
name="mobilenumber" id="mobilenumber" placeholder="+8801970112211" value="+880" pattern="^[+]\d{3}\d{4}\d{3}\d{3}$" oninvalid="this.setCustomValidity('Please enter a valid mobile number.')"
   oninput="setCustomValidity('')"/>
						</div>

					</div>
				</div>
			</fieldset>
			<div class="actions-toolbar col-lg-12 col-md-12 col-sm-12 col-xs-12 reg_para">
			<p>By <b>Registering</b>, you agree that you've read and accepted our 
			<a href="#" style="color:#356ae7"><span>User Agreement</span></a>, you're at least 18 years old, and you consent to our 
			<a href="#" style="color:#356ae7"><span>Privacy Notice</span></a> and receiving marketing communications from us.</p>
				<div class="primary register_btn btn_custom_sign">

					<button onclick="mobileNumber()" type="submit" class="login_verify action btn submit primary"
						title="<?php /* @escapeNotVerified */ echo __('Create an Account') ?>">
						<span><?php /* @escapeNotVerified */ echo __('Get verification code') ?></span>
					</button>
				</div>

				<div class="block_tit">
                    <div class="block_new_tit">
                    <h5 id="block-new-customer-heading" aria-level="2"><?php /* @escapeNotVerified */ echo __('Already have an account?') ?></h5>
                    </div>

                    <div class="block-content" aria-labelledby="block-new-customer-heading">
                        <div class="actions-toolbar action_custom_tools">
                            <div class="primary btn btn-custom2">
                                <a href="<?php echo $this->getUrl('customer/account/login'); ?>" class="action create primary">
                                <span><?php /* @escapeNotVerified */ echo __('Sign in') ?></span></a>
                            </div>
                        </div>
                    </div>
                </div>

			</div>
		</form>
	</div>
</div>


<!--<div class="col-lg-5 col-md-5 col-sm-12 col-xs-12 register_img">
	<img class="img-responsive" src="<?php echo $block->getViewFileUrl('Magento_Catalog::images/registration.png')?>">
</div>-->

</div>

<div class="container-fluid">
    <div class="signIn_footer">
      <div class="signIn_footer_nav">
        <ul>
          <li><a href="#">Conditions of Use</a></li>
          <li><a href="#">Privacy Notice</a></li>
          <li><a href="#">Help</a></li>
        </ul>
      </div>

      <div class="copyright_blk_new">
        <p>© 2016-2017 kikinben.com | The Kikinben logo is a Registered Trademark of Kikinben</p>
      </div>
    </div>
  </div>

<!-- <script>

require(
        ['jquery'],
        function($){
        	var regex = /(<([^>]+)>)/ig;
        	

        	$(".dropdown img.flag").addClass("flagvisibility");

            $(".dropdown dt a").click(function() {
                $(".dropdown dd ul").toggle();
            });
                        
            $(".dropdown dd ul li a").click(function() {
                var text = $(this).html();
                var result = text.replace(regex, "");
                var mobileNumberText = result.replace(/\s+/g, '');
                var splitNumber = mobileNumberText.split("+");
                
                $(".dropdown dt a span").html(text);
                $(".dropdown dd ul").hide();
                $("#result").html("Selected value is: " + getSelectedValue("sample"));
                $("#mobilenumber").val('+'+splitNumber[1]);
            });
                        
            function getSelectedValue(id) {
                return $("#" + id).find("dt a span.value").html();
            }

            $(document).bind('click', function(e) {
                var $clicked = $(e.target);
                if (! $clicked.parents().hasClass("dropdown"))
                    $(".dropdown dd ul").hide();
            });

           $(".dropdown img.flag").toggleClass("flagvisibility");
        	 

    }); 

</script>-->

<script type="text/javascript">
    function OnDropDownChange(dropDown) {
        var selectedValue = dropDown.options[dropDown.selectedIndex].value;
        document.getElementById("mobilenumber").value = selectedValue;
    }
 </script>

<!-- <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script> -->

<script>
function mobileNumber() {
    var x, text;
    // Get the value of the input field with id="numb"
    x = document.getElementById("numb").value;
    var phoneno = /^\+?([0-9]{2})\)?[-. ]?([0-9]{4})[-. ]?([0-9]{4})$/; 
    // If x is Not a Number or less than one or greater than 10
    if (isNaN(x) || x < 1 || x > 14) {
        alert("Input not valid");
    } else {
        text = "Input OK";
    }
}
</script>
 
<!-- <script>
jQuery(function() {
	$('select.data-list-input-code').focus(function() {
		$(this).siblings('input.data-list-input-code').focus();
	});
	$('select.data-list-input-code').change(function() {
		$(this).siblings('input.data-list-input-code').val($(this).val());
	});
    
	$('input.data-list-input-code').change(function() {
		$(this).siblings('select.data-list-input-code').val('');
	});
});



</script> -->
<script>
require([ 'jquery', 'intlTelInput'], function($){
  $(document).ready(function(){
   	$("#mobilenumber").intlTelInput({
		//excludeCountries: ["us"],
		//onlyCountries: ['us', 'gb', 'ch', 'ca', 'do', 'in'],
	});
  });
});
</script>
