<?php
$formurl = $block->getUrl('registration/index/verifyotp');
?>
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 mob_log">

	<!--<div class="col-lg-5 col-md-5 col-sm-12 col-xs-12 register_img">
		<img class="img-responsive" src="<?php echo $block->getViewFileUrl('Magento_Catalog::images/registration.png')?>">
	</div>-->

	<div class="col-lg-7 col-md-7 col-sm-12 col-xs-12">
		<div class="col-lg-9 col-md-9 col-sm-12 col-xs-12 block mob_form">


			<form class="form1" action="<?php echo $formurl?>" method="post"
				id="form-validate" enctype="multipart/form-data" autocomplete="off">

				<div class="block-title">
			        <h3 id="block-customer-login-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo __('Welcome to KiKinben') ?></h3>
			    </div>

				<fieldset class="fieldset create account verify_otp_l"
					data-hasrequired="<?php echo __('* Required Fields') ?>">
					<div class="field my_attribute required">
						<label for="mobilenumber" class="label"><span><?php echo __('Enter verification code') ?></span></label>
						<div class="control">
							<input type="text" placeholder="Enter Verification Code" name="otpnumber" id="otpnumber"
								title="<?php echo __('OTP') ?>" class="input-text"
								data-validate="{required:true}" autocomplete="off">
						</div>
					</div>
				</fieldset>
				
				<div class="actions-toolbar">
					<div class="primary btn-custom">
						<button type="submit" class="login_verify action submit primary"
							title="<?php /* @escapeNotVerified */ echo __('Verify now') ?>">
							<span><?php /* @escapeNotVerified */ echo __('Verify now') ?></span>
						</button>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>
