<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>


<?php 
$cartUrl = $block->getUrl('checkout/cart', ['_secure' => true]);
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$storeUrl =  $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);

$objectManagerRegistry = \Magento\Framework\App\ObjectManager::getInstance();
$productCurent = $objectManagerRegistry->get('Magento\Framework\Registry')->registry('current_product');//get current product
$productId = $productCurent->getId();
$productType = $productCurent->getTypeId();


$currentProduct = $block->getRelatedProductCollection($productId);


$itemCollection = $currentProduct->getRelatedProductCollection()->addAttributeToSelect(
		'required_options'
		)->setPositionOrder()->addStoreFilter()->load();

		
		
		foreach ($itemCollection as $productDetails) {
			$productDetailsAll[] = $productDetails->getData() ;
		}
?>
<?php
if ($productType === 'simple') {
?>
        <!--<div id="popup-mpdal">
            <div id="loginModal" tabindex="-1" role="dialog" aria-labelledby="loginModalLabel" aria-hidden="true">
				<div >
					<div >
						<div >
							
							<div >
								
								<div class="related_products" >
                                    <div class="col-lg-1 check_custom">
                                        <i class="fa fa-check-circle"></i> 
                                    </div>
                                    <div class="col-lg-11 pop_titile">


										<h4  id="loginModalLabel">A new item has been added to your Shopping Cart. You now have 1 items in your Shopping Cart.</h4>
									</div>
									<div >
										<input type="button" class="popup-button"  name="" value="View Shopping Cart" onclick="location.href='<?php echo $cartUrl;?>'">
                        <input type="button" class="popup-button" name="" value="Continue Shopping" onclick="location.href='<?php echo $block->getCurrentUrl();?>'">
									</div>
								</div>

							</div>
                        </div>
                        <?php if(!empty($productDetailsAll)):?>

                        <div class="pop_scroll_title">
                            <h3>Buyers Who Bought This Item Also Bought:</h3>
                        </div>

						<div class="modal-body">

    					<div id="owl-demo" class="product-carosoul">						
        						<?php 
        						foreach($productDetailsAll as $key => $val){
        							
        							$relatedId = $val['entity_id']; 
        							$details = $block->getProductImageDetails($relatedId);
        							$name = $details['name'];
        							$image = $details['image'];
        							$price = $details['price'];
        							$imageUrl ='catalog/product'.$image;
        							?>
        						<div class="single-product">
        	     					<div class="item">
        	     					     <img src="<?php echo $storeUrl.$imageUrl;?>" alt="Owl Image">
        	     					</div> 
        							<div class="name"><?php echo $name;?></div>	
        							<div class="price"><?php echo $price;?></div>	
        						</div>    
            					
        							
        						<?php
        							
        						}
        						
        						?>
    						</div>
                        </div>
                        
                    <?php endif;?>

					</div>
				</div>
			</div>
			
			
        </div>-->
<?php } ?>


<div id="demoContainer">
<div id="popup-modal">
</div>
</div>

<?php $_product = $block->getProduct(); ?>


<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()): ?>
        <div class="field qty details_qty_l">
            <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Quantity: ') ?></span></label>
            <div class="control">
            	<button type="button" class="reduced items" onclick="var result = document.getElementById('qty'); var qty = result.value; if( !isNaN( qty ) &amp;&amp; qty > 1 ) result.value--;return false;">
					<i class="fa fa-minus"></i>
				</button>
                <input type="number"
                       name="qty"
                       id="qty"
                       maxlength="12"
                       value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>"
                       title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty"
                       data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
                <button type="button" class="increase items" onclick="var result = document.getElementById('qty'); var qty = result.value; if( !isNaN( qty )) result.value++;return false;">
					<i class="fa fa-plus"></i>
				</button>
            </div>
        </div>
        <?php endif; ?>
        <!--<div class="actions">-->
        <div class="actions prod_detail_btn_l">
            <button type="submit"
                    title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                    class="action primary tocart"
                    id="product-addtocart-button">
                <i class="icon icon-add-to-cart"></i>
                	<span><?php echo $buttonTitle ?></span>
            </button>
            <?php echo $block->getChildHtml('', true) ?>
        </div>
        <!--</div>-->
       </div>
    </div>
<?php endif; ?>
<?php if ($block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php else : ?>
<script>
    require([
        'jquery',
        'mage/mage',
        'Magento_Catalog/product/view/validation',
        'Magento_Catalog/js/catalog-add-to-cart'
    ], function ($) {
        'use strict';

        $('#product_addtocart_form').mage('validation', {
            radioCheckboxClosest: '.nested',
            submitHandler: function (form) {
                var widget = $(form).catalogAddToCart({
                    bindSubmit: false
                });

                widget.catalogAddToCart('submitForm', $(form));
                return false;
            }
        });

    });

   /* require(
            [
                'jquery',
                'Magento_Ui/js/modal/modal',
		
            ],
            function(
                $,
                modal
            ) {
                var options = {
                    type: 'popup',
                    responsive: true,
                    innerScroll: true,
                    title: '',
                    buttons: [{
                       
                        class: '',
                        click: function () {
                            this.closeModal();
                        }
                    }]
                };
                var popup = modal(options, $('#popup-mpdal'));
                $("#product-addtocart-button").click(function() {
                	$('#popup-mpdal').modal('openModal');

                });                
            }
	
	

    );

    function closeit(){ 
    document.getElementById('avviso').setAttribute("style", "display:none");
} */

require([
'jquery'
],function ($) {

$(document).ready(function()
{
    $('#demoContainer').mouseup(function(e)
    {
        var subject = $("#popup-modal"); 

        if(e.target.id === 'fade')
        {
            subject.fadeOut();
		
        }
    });
    
});



});

</script>
<?php endif; ?>



