<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var $block \Magento\Customer\Block\Account\Forgotpassword
 */

// @codingStandardsIgnoreFile
?>


<div class="login-container">
<div class="col-lg-7 col-md-7 col-sm-12 col-xs-12 block forgot_pass1 ">
<div class="col-lg-8 col-md-8 col-sm-12 col-xs-12 form_cont">
<div class="block-title pass_asst">
    <h3 id="block-customer-login-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo __('Password assistance') ?></h3>
</div>
<form class="form password forget"
      action="<?php /* @escapeNotVerified */ echo $block->getUrl('*/*/forgotpasswordpost') ?>"
      method="post"
      id="form-validate"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
        <div class="field note"><?php /* @escapeNotVerified */ echo __('Please enter your email address below to receive a password reset link.'); ?></div>
        <div class="field email required">
            <label for="email_address" class="label"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></label>
            <div class="control">
                <input type="email" name="email" alt="email" id="email_address" class="input-text" value="<?php echo $block->escapeHtml($block->getEmailValue()) ?>" data-validate="{required:true, 'validate-email':true}">
            </div>
        </div>

        <div class="field mobilenumber required">
            <label for="mobilenumber" class="label"><span><?php /* @escapeNotVerified */ echo __('Mobile Number') ?></span></label>
            <div class="control">
                <input type="text" name="mobilenumber" alt="mobilenumber" id="mobile_number" class="input-text" value="<?php echo $block->escapeHtml($block->getCustomerMobile()) ?>" data-validate="{required:false, 'validate-mobile':true}">
            </div>
        </div>

        <?php echo $block->getChildHtml('form_additional_info'); ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary"><span><?php /* @escapeNotVerified */ echo __('Reset My Password') ?></span></button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?php /* @escapeNotVerified */ echo $block->getLoginUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Go back') ?></span></a>
        </div>
    </div>
</form>
</div>
</div>

<div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 sign_image">
    <img class="img-responsive" src="<?php echo $block->getViewFileUrl('Magento_Catalog::images/pass.png')?>">
</div>

</div>
<?php
$block->unsetCustomerMobile();
?>
