<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var $block \Magento\Customer\Block\Account\Forgotpassword
 */
// @codingStandardsIgnoreFile
?>


<div class="login-container pass_form_bot">

    <a href="<?php echo $block->getBaseUrl(); ?>">
        <span>
            <img class="img-responsive logo_tm_l" src="<?php echo $block->getViewFileUrl('Magento_Catalog::images/logo_tm.png')?>">
        </span>
      </a>

<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 block forgot_pass1 ">


<div class="form_cont pass_forg_marg">
<div class="block-title pass_asst">
    <h3 id="block-customer-login-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo __('Password assistance') ?></h3>
</div>
<form class="form password forget form_sign_pass"
      action="<?php /* @escapeNotVerified */ echo $block->getUrl('*/*/forgotpasswordpost') ?>"
      method="post"
      id="form-validate"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
        <div class="field note"><?php /* @escapeNotVerified */ echo __('Please enter your mobile number below to reset your password'); ?></div>
        <!-- <div class="field email required">
            <label for="email_address" class="label"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></label>
            <div class="control">
                <input type="email" name="email" alt="email" id="email_address" class="input-text" value="<?php echo $block->escapeHtml($block->getEmailValue()) ?>" data-validate="{required:true, 'validate-email':true}">
            </div>
        </div> -->

        <div class="field mobilenumber required">
            <label for="mobilenumber" class="label"><span><?php /* @escapeNotVerified */ echo __('Mobile Number*') ?></span></label>
            <div class="control">
                <input type="text" name="mobilenumber" alt="mobilenumber" id="mobile_number" class="input-text" value="<?php echo $block->escapeHtml($block->getCustomerMobile()) ?>" data-validate="{required:false, 'validate-mobile':true}">
            </div>
        </div>

        <?php echo $block->getChildHtml('form_additional_info'); ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary btn-custom">
            <button type="submit" class="action submit primary"><span><?php /* @escapeNotVerified */ echo __('Reset my password') ?></span></button>
        </div><!-- 
        <div class="secondary">
            <a class="action back" href="<?php /* @escapeNotVerified */ echo $block->getLoginUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Go back') ?></span></a>
        </div> -->
    </div>
</form>
</div>
</div>

</div>



<div class="container-fluid">
    <div class="signIn_footer">
      <div class="signIn_footer_nav">
        <ul>
          <li><a href="#">Conditions of Use</a></li>
          <li><a href="#">Privacy Notice</a></li>
          <li><a href="#">Help</a></li>
        </ul>
      </div>

      <div class="copyright_blk_new">
        <p>© 2017, kikinben.com | All Rights Reserved</p>
      </div>
    </div>
  </div>
  

<?php
$block->unsetCustomerMobile();
?>
