<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /* @var $block \Magento\Catalog\Block\Product\View\AbstractView */?>
<?php $_product = $block->getProduct() ?>

<?php if ($block->displayProductStockStatus()): ?>
    <?php if ($_product->isAvailable()): ?>
        <div class="stock available" title="<?php echo __('Availability') ?>">
            <label>Availability: </label><span><?php echo __('In stock') ?></span>
        </div>
    <?php else: ?>
        <div class="stock unavailable" title="<?php  echo __('Availability') ?>">
            <label>Availability: </label><span><?php  echo __('Out of stock') ?></span>
        </div>
    <?php endif; ?>
<?php endif; ?>

<div class="custom_sku_ki">
<h2 style="margin-top: 4px; color: #777;">SKU: <?php echo nl2br($_product->getSku()) ?></h2>
</div>
