<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>

<div class="checkout_page_cust_n">
<div class="checkout_cust_logo">
<a href="<?php echo $block->getBaseUrl(); ?>"><span><img class="img-responsive logo_tm_l_t" src="<?php echo $block->getViewFileUrl('Magento_Catalog::images/logo_tm.png')?>"></span></a>
</div>

<div id="checkout" data-bind="scope:'checkout'" class="checkout-container">
    <div id="checkout-loader" data-role="checkout-loader" class="loading-mask" data-mage-init='{"checkoutLoader": {}}'>
        <div class="loader">
            <img src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
                 alt="<?php /* @escapeNotVerified */ echo __('Loading...'); ?>"
                 style="position: absolute;">
        </div>
    </div>

    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#checkout": {
                "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
            }
        }
    </script>
    <script>
        window.checkoutConfig = <?php /* @escapeNotVerified */ echo \Zend_Json::encode($block->getCheckoutConfig()); ?>;
        // Create aliases for customer.js model from customer module
        window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
        window.customerData = window.checkoutConfig.customerData;
    </script>
    <script>
        require([
            'mage/url',
            'Magento_Ui/js/block-loader'
        ], function(url, blockLoader) {
            blockLoader("<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>");
            return url.setBaseUrl('<?php /* @escapeNotVerified */ echo $block->getBaseUrl();?>');
        })
    </script>
</div>
    
    
    <div class="checkout_footer_new_l">
            <div class="check_out_total_value">

                <span class="col-lg-12 col-md-12 col-sm-12 col-xs-12 checkout_amount_l cart-text">
                    <span class="cart-count text_value_size">Your Order Total: 
                        <span class="text_value_size">
                        <?php 
                            $helper = $this->helper('\Magento\Checkout\Helper\Cart');
                            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                            $currencysymbol = $objectManager->get('Magento\Store\Model\StoreManagerInterface');
                            $currency = $currencysymbol->getStore()->getCurrencyCode();
                            echo $currency.'TK'.' '.number_format($helper->getQuote()->getSubtotal(),2,'.', ',');?>
                     
                        </span>
                    </span> 
                </span>
                <div><h2>By placing your order, you agree to Kikinben's <a href="<?php echo $this->getUrl('privacy-notice');?>" target="_blank">Privacy Notiec</a> &amp; <a href="<?php echo $this->getUrl('conditions-of-use');?>" target="_blank">Conditon of Use</a> and other terms &amp; conditions.</h2></div>
            </div>

<div class="container cust_check_out_text_l">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 cust_check_out_l">
         

                <span>Need help? Check our Help pages or contact us
                    When you click the "Place order" button, we'll send you an e-mail message acknowledging receipt of your order. Your contract to purchase an item will not be complete until we send you an e-mail to indicate that the item has been dispatched.
                    Within 30 days of delivery, you may return new, unopened physical merchandise in its original condition. Exceptions and restrictions apply. See Kikinben's Return Policy. </span>

         <!-- <div class="signIn_footer_nav checkout_sign_cond">
            <ul>
              <li><a href="<?php echo $this->getUrl('conditions-of-use');?>">Conditions of Use</a></li>
              <li><a href="<?php echo $this->getUrl('privacy-notice');?>">Privacy Notice</a></li>
              <li><a href="<?php echo $this->getUrl('faq-new');?>">Help</a></li>
            </ul>
        </div> -->
    </div>
</div>
</div>
    

</div>



