<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
/** @var $block \Magento\Framework\View\Element\Html\Links */
?>
<?php /** @var $block \Magento\Customer\Block\Account\Navigation */ ?>
<div class="block account-nav user_acc_nav_bar_ki">
    <div class="title nav_title_ki_l">
        <strong><?php /* @escapeNotVerified */ echo __('Your Account'); ?></strong>
    </div>
    <div class="content">
        <nav class="account-nav">
            <ul class="nav items account_dashboard_cust_l">
                <?php echo $block->getChildHtml();?>
            </ul>
        </nav>
    </div>
</div>
