
<?php
$cartUrl = $block->getUrl('checkout/cart', ['_secure' => true]);
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$storeUrl =  $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$productId = $this->getData('product_id');
$currentProduct = $block->getRelatedProductCollection($productId);

$itemCollection = $currentProduct->getRelatedProductCollection()->addAttributeToSelect(
		'required_options'
		)->setPositionOrder()->addStoreFilter()->load();		
		
		foreach ($itemCollection as $productDetails) {
			$productDetailsAll[] = $productDetails->getData() ;
		}

 
?>

<script>
document.getElementById('light').style.display='block';
document.getElementById('fade').style.display='block'
</script>

<div id="light" class="white_content">
   This is the lightbox content.   
  </div>
  <div id="fade" class="black_overlay"></div>

           <!-- <div id="loginModal" tabindex="-1" role="dialog" aria-labelledby="loginModalLabel" aria-hidden="true">
				<div >
					<div >
						<div >
							
							<div >
								
								<div class="related_products" >
                                    <div class="col-lg-1 check_custom">
                                        <i class="fa fa-check-circle"></i> 
                                    </div>
                                    <div class="col-lg-11 pop_titile">


										<h4  id="loginModalLabel">A new item has been added to your Shopping Cart. You now have 1 items in your Shopping Cart.</h4>
									</div>
									<div >
										<input type="button" class="popup-button"  name="" value="View Shopping Cart" onclick="location.href='<?php echo $cartUrl;?>'">
                        <input type="button" class="popup-button" name="" value="Continue Shopping" onclick="location.href='<?php echo $block->getCurrentUrl();?>'">
									</div>
								</div>

							</div>
                        </div>
                        <?php if(!empty($productDetailsAll)):?>

                        <div class="pop_scroll_title">
                            <h3>Buyers Who Bought This Item Also Bought:</h3>
                        </div>

						<div class="modal-body">

    						<div id="owl-demo" class="product-carosoul">						
        						<?php 
        						foreach($productDetailsAll as $key => $val){
        							
        							$relatedId = $val['entity_id']; 
        							$details = $block->getProductImageDetails($relatedId);
        							$name = $details['name'];
        							$image = $details['image'];
        							$price = $details['price'];
        							$imageUrl ='catalog/product'.$image;
        							?>
        						<div class="single-product">
        	     					<div class="item">
        	     					     <img src="<?php echo $storeUrl.$imageUrl;?>" alt="Owl Image">
        	     					</div> 
        							<div class="name"><?php echo $name;?></div>	
        							<div class="price"><?php echo $price;?></div>	
        						</div>    
            					
        							
        						<?php
        							
        						}
        						
        						?>
    						</div>
                        </div>
                        
                    <?php endif;?>

					</div>
				</div>
			</div>-->
			
		
<style>
.black_overlay {
  display: none;
  position: absolute;
  top: 0%;
  left: 0%;
  width: 100%;
  height: 100%;
  background-color: black;
  z-index: 1001;
  -moz-opacity: 0.8;
  opacity: .80;
  filter: alpha(opacity=80);
}
.white_content {
  display: none;
  position: absolute;
  top: 25%;
  left: 25%;
  width: 50%;
  height: 50%;
  padding: 16px;
  border: 16px solid orange;
  background-color: white;
  z-index: 1002;
  overflow: auto;
}

</style>
<script>
// When the user clicks on <div>, open the popup
//$('#light').show();
</script>
