<?php
/**
 * Magiccart 
 * @category 	Magiccart 
 * @copyright 	Copyright (c) 2014 Magiccart (http://www.magiccart.net/) 
 * @license 	http://www.magiccart.net/license-agreement.html
 * @Author: DOng NGuyen<nguyen@dvn.com>
 * @@Create Date: 2016-02-08 22:57:12
 * @@Modify Date: 2016-07-04 17:44:09
 * @@Function:
 */
 ?>
<?php

// $_aloHelper = $this->helper('Magiccart\Magicmenu\Helper\Data');
// var_dump($_aloHelper->getConfig('magicmenu'));
$accordion = $this->_sysCfg->accordion;
if(!$accordion['enabled']) return;
// drawMainMenu vs DrowMobileMenu

$seller = $this->getRequest()->getControllerName();
$viewseller = $this->getRequest()->getActionName(); 
$customerId = $this->getRequest ()->getParam ( 'id' );



if($seller === 'seller' && $viewseller === 'displayseller'){
    $menuHtml =$this->appthaSellerCategoryList($customerId);
    $mobileMenu = $menuHtml['mobile'];
?>
<div id="aptha_marketplace_sellers">
<div class="accordion-container">
	<div class="meanmenu-accordion">
		<h3 class="accor-title"><?php echo __($this->getRootName())?></h3>
		<ul class="accordion nav-accordion" data-alo-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
			<?php echo $mobileMenu ?>
		</ul>	
		<div class="all-cat"><span><?php echo __('All Categories')?></span><span style="display:none"><?php echo __('Close')?></span></div>
	</div>
</div>
</div>
<?php
}else if($seller === 'index' && $viewseller === 'index'){
    $menuHtml =$this->appthaSellerCategoryListFiltered($customerId);
    $mobileMenu = $menuHtml['mobile'];
?>
<div class="accordion-container">
	<div class="meanmenu-accordion">
		<h3 class="accor-title"><?php echo __($this->getRootName())?></h3>
		<ul class="accordion nav-accordion" data-alo-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
			<?php echo $mobileMenu ?>
		</ul>	
		<div class="all-cat"><span><?php echo __('All Categories')?></span><span style="display:none"><?php echo __('Close')?></span></div>
	</div>
</div>
<?php
}
else{
    $menuHtml = $this->drawMainMenu();
    $mobileMenu = $menuHtml['mobile'];
?>
<div class="accordion-container">
	<div class="meanmenu-accordion">
		<h3 class="accor-title"><?php echo __($this->getRootName())?></h3>
		<ul class="accordion nav-accordion" data-alo-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
			<?php echo $mobileMenu ?>
		</ul>	
		<div class="all-cat"><span><?php echo __('All Categories')?></span><span style="display:none"><?php echo __('Close')?></span></div>
	</div>
</div>

<?php
}
?>
<script type="text/javascript">
	require(['jquery','magiccart/easing','magicmenu']);

	require([
		'jquery'
		],function ($) {

		$(document).ready(function()
		{
		    $('#aptha_marketplace_sellers div.accordion-container.mean-container div.mean-bar nav.mean-nav ul.accordion nav-accordion li.level0 nav-1 first a.level-top').bind('click', function() 
		    {
		        alert('111');
		    });
		    
		});

		});
</script>

