<?php
/**
 * Magiccart 
 * @category 	Magiccart 
 * @copyright 	Copyright (c) 2014 Magiccart (http://www.magiccart.net/) 
 * @license 	http://www.magiccart.net/license-agreement.html
 * @Author: DOng NGuyen<nguyen@dvn.com>
 * @@Create Date: 2016-02-08 22:57:12
 * @@Modify Date: 2016-08-05 16:04:43
 * @@Function:
 */
 ?>
<?php

//$_aloHelper = $this->helper('Magiccart\Magicmenu\Helper\Data');
// var_dump($_aloHelper->getConfig('magicmenu'));
$menu = $this->_sysCfg->topmenu;
$vmenu = $this->_sysCfg->vmenu;
if(!$menu['enabled']) return;

// drawMainMenu vs DrowMobileMenu
//$menuHtml = $this->drawMainMenu();
//custom code added by Apptha in app/code/Magiccart/Magicmenu/Block/Menu.php
$menuHtml = $this->appthaDrawMainMenu();
//custom code ends
$mobileMenu = $menuHtml['mobile'];
$desktop 	= $menuHtml['desktop'];
$vdesktop 	= $menuHtml['desktop'];
$ids  = explode(',', $menu['notIncludeNav']);
$vids  = explode(',', $vmenu['notIncludeNav']);
foreach ($ids as $id) { unset($desktop[$id]); }
foreach ($vids as $vid) { unset($vdesktop[$vid]); }
// drawHomeMenu
$drawHomeMenu 	= $menu['home'] ? $this->drawHomeMenu() : '';
$vdrawHomeMenu 	= $vmenu['home'] ? $this->drawHomeMenu() : '';
// drawMainMenu
$drawMainMenu 	= $menu['mainCat'] ? implode("\n", $desktop) : '';
$vdrawMainMenu 	= $vmenu['mainCat'] ? implode("\n", $vdesktop) : '';
// drawExtMenu ExtraMenu
$drawExtraMenu 	= $menu['extraCat'] ? $this->drawExtraMenu() : '';
$vdrawExtraMenu = $vmenu['extraCat'] ? $this->drawExtraMenu() : '';

?>
<?php if($vmenu['enabled']): ?> 
<div class="vmagicmenu vertical-menu clearfix">
	<div class="block-title block-title-vmagicmenu">
	  <strong>
	  	<span class="cat_shop_l">Shop By</span>
	  	<span class="acc_arr_l shop_categories_cust_l vmagicmenu-subtitl"><?php echo __($this->getRootName())?></span>
	</strong>
	</div>
	
	<div class="block-vmagicmenu-content">
		<ul class="nav-desktop vmagicmenu-narrow clearfix">
			<?php echo $vdrawHomeMenu ?>
			<?php echo $vdrawMainMenu ?>
			<?php echo $vdrawExtraMenu ?>
		</ul>
		<!--<div class="all-cat"><span><?php echo __('All Categories')?></span><span style="display:none"><?php echo __('Close')?></span></div>-->
	</div>
</div>
<?php endif ?>
<div class="magicmenu categories_cust clearfix top_nav_cust">
	
	<ul class="nav-desktop <?php echo $menu['sticker'] ? 'sticker' : '' ?>">
		<li class="dropdown_top_nav">
			<a onmouseover="popsupveggie(this);" href="#" class="dropbtn_top_nav top_nav_arrow">Today's Deals</a>
			<div class="dropdown_top_nav-content">
				<div class="col-lg-3 col-md-3 col-sm-3 veggie_drop_cont">
					<h1>Men's Clothing</h1>
					<ul>
						<li><a href="#">Shirt</a></li>
						<li><a href="#">T-Shirt</a></li>
						<li><a href="#">Pants</a></li>
						<li><a href="#">Shoes</a></li>
					</ul>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-3 veggie_drop_cont">
					<h1>Women's Clothing</h1>

					<ul>
						<li><a href="#">Salwar Kameez</a></li>
						<li><a href="#">T-Shirt &amp; Tops</a></li>
						<li><a href="#">Palazzo</a></li>
					</ul>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-3 veggie_drop_cont">
					<h1>Makeup &amp; Glam</h1>

					<ul>
						<li><a href="#">Face</a></li>
						<li><a href="#">Eyes</a></li>
						<li><a href="#">Lips</a></li>
						<li><a href="#">Hair</a></li>
					</ul>
				</div>
			</div>
		</li>
		<li class="dropdown_top_nav">
			<a onmouseover="popsupveggie(this);" href="#" class="dropbtn_top_nav top_nav_arrow">Mackup &amp; Glam</a>
			<div class="dropdown_top_nav-content">
				<div class="col-lg-3 col-md-3 col-sm-3 veggie_drop_cont">
					<h1>Face</h1>

					<ul>
						<li><a href="#">Primer</a></li>
						<li><a href="#">Foundation</a></li>
						<li><a href="#">Concealer</a></li>
						<li><a href="#">Face Powder</a></li>
						<li><a href="#">Contouring</a></li>
						<li><a href="#">Brushes</a></li>
					</ul>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-3 veggie_drop_cont">
					<h1>Eyes</h1>

					<ul>
						<li><a href="#">Eyeshadow</a></li>
						<li><a href="#">Eyeliner</a></li>
						<li><a href="#">Lashes &amp; Mascara</a></li>
						<li><a href="#">Brow</a></li>
						<li><a href="#">Eye Primer</a></li>
					</ul>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-3 veggie_drop_cont">
					<h1>Lips</h1>

					<ul>
						<li><a href="#">Liquid Lipstick</a></li>
						<li><a href="#">Lip Gloss</a></li>
					</ul>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-3 veggie_drop_cont">
					
				</div>
			</div>
		</li>
		<li class="dropdown_top_nav">
			<a onmouseover="popsupveggie(this);" href="#" class="dropbtn_top_nav top_nav_arrow">Women</a>
			<div class="dropdown_top_nav-content">
				<div class="col-lg-3 col-md-3 col-sm-3 veggie_drop_cont">
					<h1>Women's Clothing</h1>

					<ul>
						<li><a href="#">Salwar Kameez</a></li>
						<li><a href="#">T-Shirt &amp; Tops</a></li>
						<li><a href="#">Palazzo</a></li>
					</ul>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-3 veggie_drop_cont">
					<h1>Women's Shoes</h1>

					<ul>
						<li><a href="#">Flats &amp; Sandals</a></li>
						<li><a href="#">Heels</a></li>
						<li><a href="#">Boots</a></li>
						<li><a href="#">Sneakers</a></li>
						<li><a href="#">Shoes Accessories</a></li>
					</ul>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-3 veggie_drop_cont">
					<h1>Jewelleries</h1>

					<ul>
						<li><a href="#">Rings</a></li>
						<li><a href="#">Earrings</a></li>
						<li><a href="#">Bangles &amp; Bracelets</a></li>
						<li><a href="#">Necklaces &amp; Pendants</a></li>
					</ul>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-3 veggie_drop_cont">
					
				</div>
			</div>
		</li>
		<li class="dropdown_top_nav">
			<a onmouseover="popsupveggie(this);" href="#" class="dropbtn_top_nav top_nav_arrow">Men</a>
			<div class="dropdown_top_nav-content">
				<div class="col-lg-3 col-md-3 col-sm-3 veggie_drop_cont">
					<h1>Men's Clothing</h1>

					<ul>
						<li><a href="#">T-Shirts</a></li>
						<li><a href="#">Polos</a></li>
						<li><a href="#">Casual Shirts</a></li>
						<li><a href="#">Formal Shirts</a></li>
						<li><a href="#">Pants</a></li>
						<li><a href="#">Coats &amp; Jackets</a></li>
						<li><a href="#">Sweaters &amp; Hoodies</a></li>
						<li><a href="#">Panjabi &amp; Sherwani</a></li>
					</ul>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-3 veggie_drop_cont">
					<h1>Men's Shoes</h1>

					<ul>
						<li><a href="#">Formal Shoes</a></li>
						<li><a href="#">Sandals &amp; Slippers</a></li>
						<li><a href="#">Sneakers &amp; Casuals</a></li>
						<li><a href="#">Loafers</a></li>
						<li><a href="#">Boots</a></li>
						<li><a href="#">Sports Shoes</a></li>
					</ul>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-3 veggie_drop_cont">
					<h1>Watches</h1>

					<ul>
						<li><a href="#">Formal Watches</a></li>
						<li><a href="#">Casual Watches</a></li>
						<li><a href="#">Smart Watches</a></li>
						<li><a href="#">LED Watches</a></li>
						<li><a href="#">Kid's Watches</a></li>
					</ul>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-3 veggie_drop_cont">
					
				</div>
			</div>
		</li>
		<li class="dropdown_top_nav">
			<a onmouseover="popsupveggie(this);" href="#" class="dropbtn_top_nav top_nav_arrow">Bags &amp; Luggages</a>
			<div class="dropdown_top_nav-content">
				<div class="col-lg-3 col-md-3 col-sm-3 veggie_drop_cont">
					<h1>Men's Bags</h1>

					<ul>
						<li><a href="#">Backpacks</a></li>
						<li><a href="#">Wallets &amp; Clutches</a></li>
						<li><a href="#">Soulder Bags</a></li>
						<li><a href="#">Handbags</a></li>
					</ul>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-3 veggie_drop_cont">
					<h1>Women's Bags</h1>

					<ul>
						<li><a href="#">Sling Bags</a></li>
						<li><a href="#">Satchels</a></li>
						<li><a href="#">Handbags</a></li>
						<li><a href="#">Wallets</a></li>
						<li><a href="#">Totes</a></li>
					</ul>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-3 veggie_drop_cont">
					<h1>Kids &amp; Baby's Bags</h1>

					<ul>
						<li><a href="#">Backpacks</a></li>
						<li><a href="#">Soulder Bags</a></li>
						<li><a href="#">Handbags</a></li>
					</ul>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-3 veggie_drop_cont">
					
				</div>
			</div>
		</li>
		<li class="dropdown_top_nav">
			<a onmouseover="popsupveggie(this);" href="#" class="dropbtn_top_nav top_nav_arrow">Gift Card</a>
			<div class="dropdown_top_nav-content">
				<div class="col-lg-3 col-md-3 col-sm-3 veggie_drop_cont">
					<h1>Birthday Gift Card</h1>

					<ul>
						<li><a href="#"></a></li>
					</ul>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-3 veggie_drop_cont">
					<h1>Wishing Gift Card</h1>

					<ul>
						<li><a href="#"></a></li>
					</ul>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-3 veggie_drop_cont">
					<h1>Welcome Gift Card</h1>

					<ul>
						<li><a href="#"></a></li>
					</ul>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-3 veggie_drop_cont">
					<h1>Gift Card</h1>

					<ul>
						<li><a href="#"></a></li>
					</ul>
				</div>
			</div>
		</li>
		<li class="dropdown_top_nav">
			<a onmouseover="popsupveggie(this);" href="#" class="dropbtn_top_nav top_nav_arrow">Sell</a>
			<div class="dropdown_top_nav-content">
				<div class="col-lg-3 col-md-3 col-sm-3 veggie_drop_cont">
					<h1>Benefits</h1>

					<ul>
						<li><a href="#"></a></li>
					</ul>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-3 veggie_drop_cont">
					<h1>How it Works</h1>

					<ul>
						<li><a href="#"></a></li>
					</ul>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-3 veggie_drop_cont">
					<h1>Pricing</h1>

					<ul>
						<li><a href="#"></a></li>
					</ul>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-3 veggie_drop_cont">
					<h1>Eligible Categories</h1>

					<ul>
						<li><a href="#"></a></li>
					</ul>
				</div>
			</div>
		</li>
		<li class="dropdown_top_nav">
			<a onmouseover="popsupveggie(this);" href="#" class="dropbtn_top_nav top_nav_arrow">Veggie Box</a>

			<div class="dropdown_top_nav-content">
				<!-- <div class="nav-arrow-cus-l">
					<div class="nav-arrow-cus-l-inner"></div>
				</div> -->
				<div class="col-lg-4 col-md-4 col-sm-4 veggie_drop_cont">
					<h1>Farm Fresh vegetable</h1>

					<ul>
						<li><a href="<?php echo $this->getUrl('customer/account/create'); ?>">Sign up now</a></li>
						<li><a href="#">Learn more</a></li>
						<li><a href="#">Veg deals</a></li>
					</ul>

				</div>

				<div class="col-lg-4 col-md-4 col-sm-4 veggie_drop_cont">
					<h1>What is Formalin?</h1>

					<ul>
						<li><a href="#"></a></li>
					</ul>

				</div>
				<div class="col-lg-4 col-md-4 col-sm-4 veggie_drop_img">
					<img class="img-responsive" src="<?php echo $block->getViewFileUrl('Magento_Catalog::images/veggie.jpg')?>">
				</div>
			</div>
		</li>
		<!-- <?php echo $drawHomeMenu ?> -->
		<!-- <?php echo $drawMainMenu ?> -->
		<!-- <?php echo $drawExtraMenu ?> -->
	</ul>
	
	<div class="navigation-mobile">
		<ul class="nav-mobile">
			<?php echo $mobileMenu ?>
			<?php echo $drawExtraMenu ?>
		</ul>		
	</div>
</div>
<nav class="navigation" role="navigation">
	<ul class="nav-mobile" data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
	</ul>
</nav>

<script type="text/javascript">
	require(['jquery','magiccart/easing','magicmenu']);
</script>

<script type="text/javascript">
	setTimeout(function(){  jQuery('#nav-signin').fadeOut(400);}, 10000);
		 function popsupveggie(obj)
		  {
		  	document.getElementById('nav-signin').style.display = 'none';
		  }

</script>
