<?php
/**
 * Magiccart 
 * @category 	Magiccart 
 * @copyright 	Copyright (c) 2014 Magiccart (http://www.magiccart.net/) 
 * @license 	http://www.magiccart.net/license-agreement.html
 * @Author: DOng NGuyen<nguyen@dvn.com>
 * @@Create Date: 2016-02-08 22:57:12
 * @@Modify Date: 2016-08-05 16:04:43
 * @@Function:
 */
 ?>
<?php

//$_aloHelper = $this->helper('Magiccart\Magicmenu\Helper\Data');
// var_dump($_aloHelper->getConfig('magicmenu'));
$menu = $this->_sysCfg->topmenu;
$vmenu = $this->_sysCfg->vmenu;
if(!$menu['enabled']) return;

// drawMainMenu vs DrowMobileMenu
//$menuHtml = $this->drawMainMenu();
//custom code added by Apptha in app/code/Magiccart/Magicmenu/Block/Menu.php
$menuHtml = $this->appthaDrawMainMenu();
//custom code ends
$mobileMenu = $menuHtml['mobile'];
$desktop 	= $menuHtml['desktop'];
$vdesktop 	= $menuHtml['desktop'];
$ids  = explode(',', $menu['notIncludeNav']);
$vids  = explode(',', $vmenu['notIncludeNav']);
foreach ($ids as $id) { unset($desktop[$id]); }
foreach ($vids as $vid) { unset($vdesktop[$vid]); }
// drawHomeMenu
$drawHomeMenu 	= $menu['home'] ? $this->drawHomeMenu() : '';
$vdrawHomeMenu 	= $vmenu['home'] ? $this->drawHomeMenu() : '';
// drawMainMenu
$drawMainMenu 	= $menu['mainCat'] ? implode("\n", $desktop) : '';
$vdrawMainMenu 	= $vmenu['mainCat'] ? implode("\n", $vdesktop) : '';
// drawExtMenu ExtraMenu
$drawExtraMenu 	= $menu['extraCat'] ? $this->drawExtraMenu() : '';
$vdrawExtraMenu = $vmenu['extraCat'] ? $this->drawExtraMenu() : '';

?>
<?php if($vmenu['enabled']): ?> 
<div class="vmagicmenu vertical-menu clearfix">
	
	<div class="block-title block-title-vmagicmenu">
	  <strong>
	  	<span class="cat_shop_l">Shop By</span>
	  	<span class="acc_arr_l shop_categories_cust_l vmagicmenu-subtitl"><?php echo __($this->getRootName())?></span>
	</strong>
	</div>
	
	<div class="block-vmagicmenu-content">
		<ul class="nav-desktop vmagicmenu-narrow clearfix">
			<?php echo $vdrawHomeMenu ?>
			<?php echo $vdrawMainMenu ?>
			<?php echo $vdrawExtraMenu ?>
		</ul>
		<!--<div class="all-cat"><span><?php echo __('All Categories')?></span><span style="display:none"><?php echo __('Close')?></span></div>-->
	</div>
</div>
<?php endif ?>
<div class="magicmenu categories_cust clearfix top_nav_cust">
	
	<ul class="nav-desktop <?php echo $menu['sticker'] ? 'sticker' : '' ?>">
		<li><a href="#">Today's Deals</a></li>
		<li><a href="#">Gift Card &amp; Top Up</a></li>
		<li><a href="#">Start Selling on KiKinben</a></li>
		<li class="dropdown_top_nav">
			<a onmouseover="popsupveggie(this);" href="#" class="dropbtn_top_nav top_nav_arrow">Veggie Box</a>

			<div class="dropdown_top_nav-content">

			<div class="nav-arrow-cus-l">
				<div class="nav-arrow-cus-l-inner"></div>
			</div>
				<div class="col-lg-6 col-md-6 col-sm-6 veggie_drop_cont">
					<h1>Farm Fresh vegetable</h1>

					<ul>
						<li><a href="<?php echo $this->getUrl('customer/account/create'); ?>">Sign up now</a></li>
						<li><a href="#">Learn more</a></li>
						<li><a href="#">Veg deals</a></li>
						<li><a href="#">What is formalin?</a></li>
					</ul>

				</div>
				<div class="col-lg-6 col-md-6 col-sm-6 veggie_drop_img">
					<img class="img-responsive" src="<?php echo $block->getViewFileUrl('Magento_Catalog::images/veggie.jpg')?>">
				</div>
			</div>
		</li>
		<!-- <?php echo $drawHomeMenu ?> -->
		<!-- <?php echo $drawMainMenu ?> -->
		<!-- <?php echo $drawExtraMenu ?> -->
	</ul>
	
	<div class="navigation-mobile">
		<ul class="nav-mobile">
			<?php echo $mobileMenu ?>
			<?php echo $drawExtraMenu ?>
		</ul>		
	</div>
</div>
<nav class="navigation" role="navigation">
	<ul class="nav-mobile" data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
	</ul>
</nav>

<script type="text/javascript">
	require(['jquery','magiccart/easing','magicmenu']);
</script>

<script type="text/javascript">
	setTimeout(function(){  jQuery('#nav-signin').fadeOut(400);}, 10000);
		 function popsupveggie(obj)
		  {
		  	document.getElementById('nav-signin').style.display = 'none';
		  }

</script>
