<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<!-- <div class="footer-container">
    <div class="footer">
        <?php //echo $block->getChildHtml() ?>
        <p class="bugs"><?php /* @escapeNotVerified */ //echo __('Help Us Keep Magento Healthy') ?> - <a
            href="http://www.magentocommerce.com/bug-tracking"
            target="_blank"><strong><?php /* @escapeNotVerified */ //echo __('Report All Bugs') ?></strong></a>
        </p>
        <address><?php /* @escapeNotVerified */ //echo $block->getCopyright() ?></address>
    </div>
</div> -->

<div class="main-footer">
	<div class="container">
		<div class="row">
		<?php echo $this->getChildHtml('main-footer'); ?>
		</div>
	</div>
</div>
<div class="footer-bottom">
	<div class="container">
		<div class="row">
			<div class="col-lg-6 col-md-6 col-sm-7 col-xs-12 pull-right">
			<!-- <div class="footer_payment"> -->
			<div class="footer_payment">
				<ul>
				 <li><a href="#"><img src="<?php echo $block->getViewFileUrl('images/bkash.png'); ?>" alt="Bkash"></a></li>
				 <li><a href="#"><img src="<?php echo $block->getViewFileUrl('images/rocket.png'); ?>" alt="Rocket"></a></li>
				 <li><a href="#"><img src="<?php echo $block->getViewFileUrl('images/master.png'); ?>" alt="master card"></a></li>
				 <li><a href="#"><img src="<?php echo $block->getViewFileUrl('images/visa.png'); ?>" alt="visa"></a></li>
				 <li><a href="#"><img src="<?php echo $block->getViewFileUrl('images/paypal1.png'); ?>" alt="paypal"></a></li>
				 <li><a href="#"><img src="<?php echo $block->getViewFileUrl('images/maestro.png'); ?>" alt="maestro"></a></li>
				</ul>
			</div>
				
				 <!-- <a href="#" class="paypal"><img src="<?php echo $block->getViewFileUrl('images/paypal.png'); ?>"></a> -->
			
			</div>
			<div class="col-lg-6 col-md-6 col-sm-5 col-xs-12 pull-left">
				<div class="copyright">
					<?php echo $this->getChildHtml('copyright'); ?>
				</div>
			</div>
		</div>
	</div>
	<a href="#" id="backtotop"><span class="fa fa-angle-up"></span><span class="back-to-top"><?php echo __('Back to Top')?></span></a>
</div>